jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the secret in a script
        run: echo DEFISTATSBACKEND
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3